"""
Report Generator
Generates Markdown and JSON reports from scan results
with MITRE ATT&CK mapping and severity scoring.
"""

import json
from datetime import datetime


class ReportGenerator:
    """Generates endpoint security reports from scan data."""

    def generate(self, scan_data, report_format='markdown'):
        """Generate a report from scan results."""
        if report_format == 'json':
            return self._generate_json(scan_data)
        else:
            return self._generate_markdown(scan_data)

    def _generate_markdown(self, scan_data):
        """Generate a Markdown report."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        hostname = scan_data.get('hostname', 'Unknown')
        os_type = scan_data.get('os', 'Unknown')

        lines = []
        lines.append(f'# EndpointForge Security Report')
        lines.append(f'')
        lines.append(f'**Generated:** {timestamp}')
        lines.append(f'**Hostname:** {hostname}')
        lines.append(f'**Operating System:** {os_type}')
        lines.append(f'**Scan Time:** {scan_data.get("scan_time", "N/A")}')
        lines.append(f'')

        # Executive Summary
        lines.append(f'## Executive Summary')
        lines.append(f'')

        total_findings = self._count_all_findings(scan_data)
        severity_counts = self._aggregate_severity(scan_data)

        lines.append(f'Total findings: **{total_findings}**')
        lines.append(f'')
        lines.append(f'| Severity | Count |')
        lines.append(f'|----------|-------|')
        for sev in ['critical', 'high', 'medium', 'low', 'info']:
            count = severity_counts.get(sev, 0)
            if count > 0:
                lines.append(f'| {sev.upper()} | {count} |')
        lines.append(f'')

        # Process Analysis
        if 'processes' in scan_data:
            lines.append(self._section_processes(scan_data['processes']))

        # Network Analysis
        if 'network' in scan_data:
            lines.append(self._section_network(scan_data['network']))

        # File System Integrity
        if 'filesystem' in scan_data:
            lines.append(self._section_filesystem(scan_data['filesystem']))

        # Registry Analysis
        if 'registry' in scan_data:
            lines.append(self._section_registry(scan_data['registry']))

        # Persistence Mechanisms
        if 'persistence' in scan_data:
            lines.append(self._section_persistence(scan_data['persistence']))

        # MITRE ATT&CK Mapping
        lines.append(self._section_mitre_mapping(scan_data))

        # Recommendations
        lines.append(self._section_recommendations(scan_data))

        lines.append(f'')
        lines.append(f'---')
        lines.append(f'*Report generated by EndpointForge v1.0.0*')

        content = '\n'.join(lines)
        return {
            'content': content,
            'format': 'markdown',
            'timestamp': timestamp,
            'total_findings': total_findings
        }

    def _generate_json(self, scan_data):
        """Generate a JSON report."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        report = {
            'report_metadata': {
                'tool': 'EndpointForge',
                'version': '1.0.0',
                'generated': timestamp,
                'hostname': scan_data.get('hostname', 'Unknown'),
                'os': scan_data.get('os', 'Unknown')
            },
            'summary': {
                'total_findings': self._count_all_findings(scan_data),
                'severity_counts': self._aggregate_severity(scan_data)
            },
            'findings': self._collect_all_findings(scan_data),
            'mitre_techniques': self._collect_mitre_techniques(scan_data),
            'raw_data': scan_data
        }

        content = json.dumps(report, indent=2)
        return {
            'content': content,
            'format': 'json',
            'timestamp': timestamp,
            'total_findings': report['summary']['total_findings']
        }

    def _section_processes(self, process_data):
        """Generate process analysis section."""
        lines = []
        lines.append(f'## Process Execution Analysis')
        lines.append(f'')
        lines.append(f'Processes scanned: **{process_data.get("process_count", 0)}**')
        lines.append(f'Findings: **{process_data.get("findings_count", 0)}**')
        lines.append(f'')

        for finding in process_data.get('findings', []):
            sev = finding.get('severity', 'info').upper()
            lines.append(f'### [{sev}] {finding.get("message", "")}')
            lines.append(f'')
            lines.append(f'- **MITRE ATT&CK:** {finding.get("mitre_id", "N/A")} — {finding.get("mitre_name", "")}')
            lines.append(f'- **Details:** {finding.get("details", "")}')
            lines.append(f'')

        return '\n'.join(lines)

    def _section_network(self, network_data):
        """Generate network analysis section."""
        lines = []
        lines.append(f'## Network Connections Analysis')
        lines.append(f'')
        lines.append(f'Active connections: **{network_data.get("connection_count", 0)}**')
        lines.append(f'Established: **{network_data.get("established_count", 0)}** | Listening: **{network_data.get("listening_count", 0)}**')
        lines.append(f'Findings: **{network_data.get("findings_count", 0)}**')
        lines.append(f'')

        for finding in network_data.get('findings', []):
            sev = finding.get('severity', 'info').upper()
            lines.append(f'### [{sev}] {finding.get("message", "")}')
            lines.append(f'')
            lines.append(f'- **MITRE ATT&CK:** {finding.get("mitre_id", "N/A")} — {finding.get("mitre_name", "")}')
            lines.append(f'- **Process:** {finding.get("process", "Unknown")} (PID: {finding.get("pid", "N/A")})')
            lines.append(f'- **Details:** {finding.get("details", "")}')
            lines.append(f'')

        return '\n'.join(lines)

    def _section_filesystem(self, fs_data):
        """Generate filesystem integrity section."""
        lines = []
        lines.append(f'## File System Integrity')
        lines.append(f'')

        changes = fs_data.get('changes', {})
        lines.append(f'New files: **{fs_data.get("new_files", 0)}** | Modified: **{fs_data.get("modified_files", 0)}** | Deleted: **{fs_data.get("deleted_files", 0)}**')
        lines.append(f'Baseline date: {fs_data.get("baseline_date", "N/A")}')
        lines.append(f'')

        for finding in fs_data.get('findings', []):
            sev = finding.get('severity', 'info').upper()
            lines.append(f'### [{sev}] {finding.get("message", "")}')
            lines.append(f'')
            lines.append(f'- **MITRE ATT&CK:** {finding.get("mitre_id", "N/A")} — {finding.get("mitre_name", "")}')
            lines.append(f'- **Details:** {finding.get("details", "")}')
            lines.append(f'')

        return '\n'.join(lines)

    def _section_registry(self, registry_data):
        """Generate registry analysis section."""
        lines = []
        lines.append(f'## Registry Modifications Analysis')
        lines.append(f'')

        if not registry_data.get('os_supported', True):
            lines.append(f'*Registry analysis is only available on Windows systems.*')
            return '\n'.join(lines)

        lines.append(f'Keys scanned: **{registry_data.get("keys_scanned", 0)}**')
        lines.append(f'Entries found: **{registry_data.get("entries_count", 0)}**')
        lines.append(f'Findings: **{registry_data.get("findings_count", 0)}**')
        lines.append(f'')

        for finding in registry_data.get('findings', []):
            sev = finding.get('severity', 'info').upper()
            lines.append(f'### [{sev}] {finding.get("message", "")}')
            lines.append(f'')
            lines.append(f'- **MITRE ATT&CK:** {finding.get("mitre_id", "N/A")} — {finding.get("mitre_name", "")}')
            lines.append(f'- **Registry Key:** {finding.get("registry_key", "")}')
            lines.append(f'- **Value Name:** {finding.get("value_name", "")}')
            lines.append(f'- **Details:** {finding.get("details", "")}')
            lines.append(f'')

        return '\n'.join(lines)

    def _section_persistence(self, persistence_data):
        """Generate persistence mechanisms section."""
        lines = []
        lines.append(f'## Persistence Mechanism Detection')
        lines.append(f'')
        lines.append(f'Mechanisms scanned: **{persistence_data.get("mechanism_count", 0)}**')
        lines.append(f'Suspicious findings: **{persistence_data.get("findings_count", 0)}**')
        lines.append(f'')

        for finding in persistence_data.get('findings', []):
            sev = finding.get('severity', 'info').upper()
            lines.append(f'### [{sev}] {finding.get("message", "")}')
            lines.append(f'')
            lines.append(f'- **MITRE ATT&CK:** {finding.get("mitre_id", "N/A")} — {finding.get("mitre_name", "")}')
            lines.append(f'- **Details:** {finding.get("details", "")}')
            lines.append(f'')

        return '\n'.join(lines)

    def _section_mitre_mapping(self, scan_data):
        """Generate MITRE ATT&CK technique summary."""
        lines = []
        lines.append(f'## MITRE ATT&CK Mapping')
        lines.append(f'')

        techniques = self._collect_mitre_techniques(scan_data)
        if techniques:
            lines.append(f'| Technique ID | Technique Name | Occurrences |')
            lines.append(f'|-------------|----------------|-------------|')
            for tech_id, info in sorted(techniques.items()):
                lines.append(f'| {tech_id} | {info["name"]} | {info["count"]} |')
        else:
            lines.append(f'No MITRE ATT&CK techniques identified.')

        lines.append(f'')
        return '\n'.join(lines)

    def _section_recommendations(self, scan_data):
        """Generate recommendations based on findings."""
        lines = []
        lines.append(f'## Recommendations')
        lines.append(f'')

        severity = self._aggregate_severity(scan_data)
        if severity.get('critical', 0) > 0:
            lines.append(f'1. **IMMEDIATE:** Investigate all CRITICAL findings. Isolate the endpoint if active compromise is suspected.')
        if severity.get('high', 0) > 0:
            lines.append(f'2. **HIGH PRIORITY:** Review HIGH severity findings for unauthorized persistence mechanisms and suspicious processes.')
        if severity.get('medium', 0) > 0:
            lines.append(f'3. **MEDIUM:** Investigate medium-severity findings to rule out false positives and unauthorized changes.')
        lines.append(f'4. Update baseline after remediation to establish new known-good state.')
        lines.append(f'5. Cross-reference findings with SIEM alerts and threat intelligence feeds.')
        lines.append(f'')

        return '\n'.join(lines)

    def _count_all_findings(self, scan_data):
        """Count total findings across all modules."""
        total = 0
        for module in ['processes', 'network', 'filesystem', 'registry', 'persistence']:
            if module in scan_data:
                total += len(scan_data[module].get('findings', []))
        return total

    def _aggregate_severity(self, scan_data):
        """Aggregate severity counts across all modules."""
        totals = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
        for module in ['processes', 'network', 'filesystem', 'registry', 'persistence']:
            if module in scan_data:
                summary = scan_data[module].get('summary', {})
                for sev in totals:
                    totals[sev] += summary.get(sev, 0)
        return totals

    def _collect_all_findings(self, scan_data):
        """Collect all findings into a single list."""
        all_findings = []
        for module in ['processes', 'network', 'filesystem', 'registry', 'persistence']:
            if module in scan_data:
                for finding in scan_data[module].get('findings', []):
                    finding['module'] = module
                    all_findings.append(finding)
        return sorted(all_findings, key=lambda x: {
            'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4
        }.get(x.get('severity', 'info'), 5))

    def _collect_mitre_techniques(self, scan_data):
        """Collect unique MITRE ATT&CK techniques from all findings."""
        techniques = {}
        for module in ['processes', 'network', 'filesystem', 'registry', 'persistence']:
            if module in scan_data:
                for finding in scan_data[module].get('findings', []):
                    tech_id = finding.get('mitre_id')
                    if tech_id:
                        if tech_id not in techniques:
                            techniques[tech_id] = {
                                'name': finding.get('mitre_name', 'Unknown'),
                                'count': 0
                            }
                        techniques[tech_id]['count'] += 1
        return techniques
